# Site Settings
title: Jason McBride
email: contact@jasonmcbride.me
description: >
  Freelance Developer & Web Enthusiast
keywords: Sault Ste. Marie, Developer, Web Designer
baseurl: ""
url: "http://localhost:4000"
twitter_username: ""
github_username:  ""
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM